### ISSUE TITLE
Improve types

### ISSUE THREAD

**Issue by chrismilson** [alkihis/iterator-polyfill#1]
In the typescript docs, `Array.prototype` has overloaded types on some of the methods.

For example, on the filter type, it has the following overload:

```typescript
filter<S extends T>(predicate: (value: T, index: number, array: T[]) => value is S, thisArg?: any): S[];
```

I would be interested in doing a pull request that adds overloads for the new iterator methods, such as this.

**Comment by alkihis** [comment]
Hi, thank you for your contribution.
It's fine for me, you can make a pull request with type adjustements.

**Comment by alkihis** [comment]
Merged and published to NPM.
